ENVIRONMENT:
  MAX_EPISODE_STEPS: 1001
  ITERATOR_OPTIONS:
    MAX_SCENE_REPEAT_STEPS: 5000
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 90
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 90
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
  ACTION_SPACE_CONFIG: "pyrobotnoisy"
  NOISE_MODEL:
    ROBOT: 'LoCoBot'
    CONTROLLER: 'ILQR'
    NOISE_MULTIPLIER: 1.0
TASK:
  TYPE: Exp-v0
  POSSIBLE_ACTIONS: ["MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  SENSORS: ['NOISY_POSE_SENSOR', 'GT_POSE_SENSOR', 'GT_EGO_MAP_ANTICIPATED', 'COLLISION_SENSOR','GT_EGO_MAP', 'GT_EGO_WALL_MAP']
  GT_EGO_MAP:
    MAP_SIZE: 261
    MAP_SCALE: 0.02
    HEIGHT_THRESH: [0.2, 1.5]
  GT_EGO_WALL_MAP:
    MAP_SIZE: 261
    MAP_SCALE: 0.02
    HEIGHT_THRESH: [1.0, 1.5]
  GT_EGO_MAP_ANTICIPATED:
    MAP_SIZE: 261
    MAP_SCALE: 0.02
    HEIGHT_THRESH: [0.2, 1.5]
    MAX_SENSOR_RANGE: 10.0
    NUM_TOPDOWN_MAP_SAMPLE_POINTS: 20000
    GT_TYPE: 'wall_occupancy'
    ALL_MAPS_INFO_PATH: data/datasets/exploration/se_bed_data/v1/train/gt_maps_semantic/all_maps_info.json
  MEASUREMENTS: []
DATASET:
  TYPE: Exploration-v1
  SPLIT: train
  DATA_PATH: data/datasets/exploration/se_bed_data/v1/{split}/{split}.json.gz